In [1]:
import numpy as np
A=np.array([[56,20,50,46],[8,10,52,41],[5,2,15,8]])
print (A)

[[56 20 50 46]
 [ 8 10 52 41]
 [ 5  2 15  8]]


In [2]:
crime=A.sum(axis=0)
print (crime)

[ 69  32 117  95]


In [3]:
perc=A/crime.reshape(1,4)
print (perc)

[[ 0.8115942   0.625       0.42735043  0.48421053]
 [ 0.11594203  0.3125      0.44444444  0.43157895]
 [ 0.07246377  0.0625      0.12820513  0.08421053]]
