In [2]:
import numpy as np
a=np.random.randn(5)
print (a)

[ 0.01933157 -0.09649279  1.16548487  1.08273727  0.6339713 ]


In [4]:
print (a.shape)


(5,)


In [5]:
print (a.T)

[ 0.01933157 -0.09649279  1.16548487  1.08273727  0.6339713 ]


In [6]:
print (a.T.shape)

(5,)


In [8]:
print (np.dot(a,a.T))

2.9422791538


In [9]:
a=np.random.randn(5,1)
print (a)

[[ 1.44041156]
 [-1.58982177]
 [ 0.24719571]
 [-1.03609154]
 [-0.97642032]]


In [10]:
print (a.T)

[[ 1.44041156 -1.58982177  0.24719571 -1.03609154 -0.97642032]]


In [11]:
print (np.dot(a,a.T))

[[ 2.07478547 -2.28999767  0.35606356 -1.49239824 -1.40644711]
 [-2.28999767  2.52753327 -0.39299712  1.64720089  1.55233428]
 [ 0.35606356 -0.39299712  0.06110572 -0.25611738 -0.24136691]
 [-1.49239824  1.64720089 -0.25611738  1.07348568  1.01166083]
 [-1.40644711  1.55233428 -0.24136691  1.01166083  0.95339663]]
